package moe.lymia.multiverse.util

import java.nio.file.{Files, Path}

import scala.xml.{PrettyPrinter, Node}

object XMLUtils {
  def getAttribute(node: Node, attribute: String) = (node \ ("@" + attribute)).text
  def getNodeText (node: Node, tag: String) = (node \ tag).text.trim
}

object IOUtils {
  def writeFile(path: Path, data: Array[Byte]) = {
    if(path.getParent != null) Files.createDirectories(path.getParent)
    Files.write(path, data)
  }

  val xmlWriter = new PrettyPrinter(Int.MaxValue, 4)
  def writeXML(path: Path, xml: Node, prettyPrint: Boolean = true) = {
    val xmlString = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"+
      "<!-- Generated by Multiverse Mod Manager -->\n"+
      (if(prettyPrint) xmlWriter.format(xml) else xml.toString)+"\n"
    writeFile(path, xmlString.getBytes("UTF-8"))
  }
}