/**
    Copyright (C) 2015 Lymia Aluysia <lymiahugs@gmail.com>

    Permission is hereby granted, free of charge, to any person obtaining a copy of
    this software and associated documentation files (the "Software"), to deal in
    the Software without restriction, including without limitation the rights to
    use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
    of the Software, and to permit persons to whom the Software is furnished to do
    so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/

// This hooks Database::XMLSerializer::LoadFromMemory to allow us to execute raw .sql
// code through .xml data files. Some mods require .sql files to function, something not
// possible in DLC files without patching.
//
// This adds two new special tags to the XML parser: <__MVMM_PATCH_IGNORE> which has all
// its contents ignored, which is used to create an canary value to force errors when
// someone tries to load one of the .sql file converted to .xml files on an unpatched copy
// of Civilization. <__MVMM_PATCH_RAWSQL> causes all its contents to be executed as SQL
// code, in the same way as the SQL code that would otherwise be generated by
// Database::XMLSerializer for normal .xml files.

#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "c_rt.h"
#include "c_defines.h"
#include "extern_defines.h"
#include "version.h"

static bool checkXmlNodeTag(class_XmlNode* xmlNode, const char* name) {
  size_t len = strlen(name);
  return XmlNode_NameMatches(xmlNode, name, &len);  
}

// Main body
bool xml_init = false;
extern __attribute__((stdcall)) bool XmlParserHookCore(class_XmlNode* xmlNode, class_Database* connection, int* success) __asm__("cif_XmlParserHookCore");
__attribute__((stdcall)) bool XmlParserHookCore(class_XmlNode* xmlNode, class_Database* connection, int* success) {
    *success = 1;

    if(!xml_init) {
        debug_print("Initialized XmlParserHook!");
        Database_LogMessage(connection, patchMarkerString);
        xml_init = true;
    }

    if(checkXmlNodeTag(xmlNode, "__MVMM_PATCH_IGNORE")) {
        return true;
    } else if(checkXmlNodeTag(xmlNode, "__MVMM_PATCH_RAWSQL")) {
        char* string;
        int   length;
        XmlNode_GetValUtf8(xmlNode, &string, &length);

        #ifdef DEBUG
            char* tmpString = malloc(length + 1);
            memcpy(tmpString, string, length);
            tmpString[length] = 0;

            debug_print("Executing XML-encapsulated SQL:\n%s", tmpString);

            free(tmpString);
        #endif

        if(!Database_ExecuteMultiple(connection, string, length)) {
            Database_LogMessage(connection,
                "Failed to execute statement while processing __MVMM_PATCH_RAWSQL tag.");
            *success = 0;
        }
        return true;
    } else {
        return false;
    }
}

extern void XmlParserHook() __asm__("cif_XmlParserHook");
UnpatchData* XmlParserPatch;
__attribute__((constructor(500))) static void installXmlHook() {
    XmlParserPatch = doPatch(XmlParserHook_offset, XmlParserHook, "XmlParserHook");
}
__attribute__((destructor(500))) static void destroyXmlHook() {
    unpatch(XmlParserPatch);
}
