// Stub lua51_Win32.dll for linking purposes.
__declspec(dllexport) void luaL_addlstring() { }
__declspec(dllexport) void luaL_addstring() { }
__declspec(dllexport) void luaL_addvalue() { }
__declspec(dllexport) void luaL_argerror() { }
__declspec(dllexport) void luaL_buffinit() { }
__declspec(dllexport) void luaL_callmeta() { }
__declspec(dllexport) void luaL_checkany() { }
__declspec(dllexport) void luaL_checkinteger() { }
__declspec(dllexport) void luaL_checklstring() { }
__declspec(dllexport) void luaL_checknumber() { }
__declspec(dllexport) void luaL_checkoption() { }
__declspec(dllexport) void luaL_checkstack() { }
__declspec(dllexport) void luaL_checktype() { }
__declspec(dllexport) void luaL_checkudata() { }
__declspec(dllexport) void luaL_error() { }
__declspec(dllexport) void luaL_findtable() { }
__declspec(dllexport) void luaL_getmetafield() { }
__declspec(dllexport) void luaL_gsub() { }
__declspec(dllexport) void luaL_loadbuffer() { }
__declspec(dllexport) void luaL_loadfile() { }
__declspec(dllexport) void luaL_loadstring() { }
__declspec(dllexport) void luaL_newmetatable() { }
__declspec(dllexport) void luaL_newstate() { }
__declspec(dllexport) void luaL_openlib() { }
__declspec(dllexport) void luaL_openlibs() { }
__declspec(dllexport) void luaL_optinteger() { }
__declspec(dllexport) void luaL_optlstring() { }
__declspec(dllexport) void luaL_optnumber() { }
__declspec(dllexport) void luaL_prepbuffer() { }
__declspec(dllexport) void luaL_pushresult() { }
__declspec(dllexport) void luaL_ref() { }
__declspec(dllexport) void luaL_register() { }
__declspec(dllexport) void luaL_typerror() { }
__declspec(dllexport) void luaL_unref() { }
__declspec(dllexport) void luaL_where() { }
__declspec(dllexport) void lua_atpanic() { }
__declspec(dllexport) void lua_call() { }
__declspec(dllexport) void lua_checkstack() { }
__declspec(dllexport) void lua_close() { }
__declspec(dllexport) void lua_concat() { }
__declspec(dllexport) void lua_cpcall() { }
__declspec(dllexport) void lua_createtable() { }
__declspec(dllexport) void lua_dump() { }
__declspec(dllexport) void lua_equal() { }
__declspec(dllexport) void lua_error() { }
__declspec(dllexport) void lua_gc() { }
__declspec(dllexport) void lua_getallocf() { }
__declspec(dllexport) void lua_getfenv() { }
__declspec(dllexport) void lua_getfield() { }
__declspec(dllexport) void lua_gethook() { }
__declspec(dllexport) void lua_gethookcount() { }
__declspec(dllexport) void lua_gethookmask() { }
__declspec(dllexport) void lua_getinfo() { }
__declspec(dllexport) void lua_getlocal() { }
__declspec(dllexport) void lua_getmetatable() { }
__declspec(dllexport) void lua_getstack() { }
__declspec(dllexport) void lua_gettable() { }
__declspec(dllexport) void lua_gettop() { }
__declspec(dllexport) void lua_getupvalue() { }
__declspec(dllexport) void lua_insert() { }
__declspec(dllexport) void lua_iscfunction() { }
__declspec(dllexport) void lua_isnumber() { }
__declspec(dllexport) void lua_isstring() { }
__declspec(dllexport) void lua_isuserdata() { }
__declspec(dllexport) void lua_lessthan() { }
__declspec(dllexport) void lua_load() { }
__declspec(dllexport) void lua_newstate() { }
__declspec(dllexport) void lua_newthread() { }
__declspec(dllexport) void lua_newuserdata() { }
__declspec(dllexport) void lua_next() { }
__declspec(dllexport) void lua_objlen() { }
__declspec(dllexport) void lua_pcall() { }
__declspec(dllexport) void lua_pushboolean() { }
__declspec(dllexport) void lua_pushcclosure() { }
__declspec(dllexport) void lua_pushfstring() { }
__declspec(dllexport) void lua_pushinteger() { }
__declspec(dllexport) void lua_pushlightuserdata() { }
__declspec(dllexport) void lua_pushlstring() { }
__declspec(dllexport) void lua_pushnil() { }
__declspec(dllexport) void lua_pushnumber() { }
__declspec(dllexport) void lua_pushstring() { }
__declspec(dllexport) void lua_pushthread() { }
__declspec(dllexport) void lua_pushvalue() { }
__declspec(dllexport) void lua_pushvfstring() { }
__declspec(dllexport) void lua_rawequal() { }
__declspec(dllexport) void lua_rawget() { }
__declspec(dllexport) void lua_rawgeti() { }
__declspec(dllexport) void lua_rawset() { }
__declspec(dllexport) void lua_rawseti() { }
__declspec(dllexport) void lua_remove() { }
__declspec(dllexport) void lua_replace() { }
__declspec(dllexport) void lua_resume() { }
__declspec(dllexport) void lua_setallocf() { }
__declspec(dllexport) void lua_setfenv() { }
__declspec(dllexport) void lua_setfield() { }
__declspec(dllexport) void lua_sethook() { }
__declspec(dllexport) void lua_setlevel() { }
__declspec(dllexport) void lua_setlocal() { }
__declspec(dllexport) void lua_setmetatable() { }
__declspec(dllexport) void lua_settable() { }
__declspec(dllexport) void lua_settop() { }
__declspec(dllexport) void lua_setupvalue() { }
__declspec(dllexport) void lua_status() { }
__declspec(dllexport) void lua_toboolean() { }
__declspec(dllexport) void lua_tocfunction() { }
__declspec(dllexport) void lua_tointeger() { }
__declspec(dllexport) void lua_tolstring() { }
__declspec(dllexport) void lua_tonumber() { }
__declspec(dllexport) void lua_topointer() { }
__declspec(dllexport) void lua_tothread() { }
__declspec(dllexport) void lua_touserdata() { }
__declspec(dllexport) void lua_type() { }
__declspec(dllexport) void lua_typename() { }
__declspec(dllexport) void lua_xmove() { }
__declspec(dllexport) void lua_yield() { }
__declspec(dllexport) void luaopen_base() { }
__declspec(dllexport) void luaopen_debug() { }
__declspec(dllexport) void luaopen_io() { }
__declspec(dllexport) void luaopen_math() { }
__declspec(dllexport) void luaopen_os() { }
__declspec(dllexport) void luaopen_package() { }
__declspec(dllexport) void luaopen_string() { }
__declspec(dllexport) void luaopen_table() { }
