// Stub lua51_Win32.dll for linking purposes.
__declspec(dllexport) __cdecl void luaL_addlstring() { }
__declspec(dllexport) __cdecl void luaL_addstring() { }
__declspec(dllexport) __cdecl void luaL_addvalue() { }
__declspec(dllexport) __cdecl void luaL_argerror() { }
__declspec(dllexport) __cdecl void luaL_buffinit() { }
__declspec(dllexport) __cdecl void luaL_callmeta() { }
__declspec(dllexport) __cdecl void luaL_checkany() { }
__declspec(dllexport) __cdecl void luaL_checkinteger() { }
__declspec(dllexport) __cdecl void luaL_checklstring() { }
__declspec(dllexport) __cdecl void luaL_checknumber() { }
__declspec(dllexport) __cdecl void luaL_checkoption() { }
__declspec(dllexport) __cdecl void luaL_checkstack() { }
__declspec(dllexport) __cdecl void luaL_checktype() { }
__declspec(dllexport) __cdecl void luaL_checkudata() { }
__declspec(dllexport) __cdecl void luaL_error() { }
__declspec(dllexport) __cdecl void luaL_findtable() { }
__declspec(dllexport) __cdecl void luaL_getmetafield() { }
__declspec(dllexport) __cdecl void luaL_gsub() { }
__declspec(dllexport) __cdecl void luaL_loadbuffer() { }
__declspec(dllexport) __cdecl void luaL_loadfile() { }
__declspec(dllexport) __cdecl void luaL_loadstring() { }
__declspec(dllexport) __cdecl void luaL_newmetatable() { }
__declspec(dllexport) __cdecl void luaL_newstate() { }
__declspec(dllexport) __cdecl void luaL_openlib() { }
__declspec(dllexport) __cdecl void luaL_openlibs() { }
__declspec(dllexport) __cdecl void luaL_optinteger() { }
__declspec(dllexport) __cdecl void luaL_optlstring() { }
__declspec(dllexport) __cdecl void luaL_optnumber() { }
__declspec(dllexport) __cdecl void luaL_prepbuffer() { }
__declspec(dllexport) __cdecl void luaL_pushresult() { }
__declspec(dllexport) __cdecl void luaL_ref() { }
__declspec(dllexport) __cdecl void luaL_register() { }
__declspec(dllexport) __cdecl void luaL_typerror() { }
__declspec(dllexport) __cdecl void luaL_unref() { }
__declspec(dllexport) __cdecl void luaL_where() { }
__declspec(dllexport) __cdecl void lua_atpanic() { }
__declspec(dllexport) __cdecl void lua_call() { }
__declspec(dllexport) __cdecl void lua_checkstack() { }
__declspec(dllexport) __cdecl void lua_close() { }
__declspec(dllexport) __cdecl void lua_concat() { }
__declspec(dllexport) __cdecl void lua_cpcall() { }
__declspec(dllexport) __cdecl void lua_createtable() { }
__declspec(dllexport) __cdecl void lua_dump() { }
__declspec(dllexport) __cdecl void lua_equal() { }
__declspec(dllexport) __cdecl void lua_error() { }
__declspec(dllexport) __cdecl void lua_gc() { }
__declspec(dllexport) __cdecl void lua_getallocf() { }
__declspec(dllexport) __cdecl void lua_getfenv() { }
__declspec(dllexport) __cdecl void lua_getfield() { }
__declspec(dllexport) __cdecl void lua_gethook() { }
__declspec(dllexport) __cdecl void lua_gethookcount() { }
__declspec(dllexport) __cdecl void lua_gethookmask() { }
__declspec(dllexport) __cdecl void lua_getinfo() { }
__declspec(dllexport) __cdecl void lua_getlocal() { }
__declspec(dllexport) __cdecl void lua_getmetatable() { }
__declspec(dllexport) __cdecl void lua_getstack() { }
__declspec(dllexport) __cdecl void lua_gettable() { }
__declspec(dllexport) __cdecl void lua_gettop() { }
__declspec(dllexport) __cdecl void lua_getupvalue() { }
__declspec(dllexport) __cdecl void lua_insert() { }
__declspec(dllexport) __cdecl void lua_iscfunction() { }
__declspec(dllexport) __cdecl void lua_isnumber() { }
__declspec(dllexport) __cdecl void lua_isstring() { }
__declspec(dllexport) __cdecl void lua_isuserdata() { }
__declspec(dllexport) __cdecl void lua_lessthan() { }
__declspec(dllexport) __cdecl void lua_load() { }
__declspec(dllexport) __cdecl void lua_newstate() { }
__declspec(dllexport) __cdecl void lua_newthread() { }
__declspec(dllexport) __cdecl void lua_newuserdata() { }
__declspec(dllexport) __cdecl void lua_next() { }
__declspec(dllexport) __cdecl void lua_objlen() { }
__declspec(dllexport) __cdecl void lua_pcall() { }
__declspec(dllexport) __cdecl void lua_pushboolean() { }
__declspec(dllexport) __cdecl void lua_pushcclosure() { }
__declspec(dllexport) __cdecl void lua_pushfstring() { }
__declspec(dllexport) __cdecl void lua_pushinteger() { }
__declspec(dllexport) __cdecl void lua_pushlightuserdata() { }
__declspec(dllexport) __cdecl void lua_pushlstring() { }
__declspec(dllexport) __cdecl void lua_pushnil() { }
__declspec(dllexport) __cdecl void lua_pushnumber() { }
__declspec(dllexport) __cdecl void lua_pushstring() { }
__declspec(dllexport) __cdecl void lua_pushthread() { }
__declspec(dllexport) __cdecl void lua_pushvalue() { }
__declspec(dllexport) __cdecl void lua_pushvfstring() { }
__declspec(dllexport) __cdecl void lua_rawequal() { }
__declspec(dllexport) __cdecl void lua_rawget() { }
__declspec(dllexport) __cdecl void lua_rawgeti() { }
__declspec(dllexport) __cdecl void lua_rawset() { }
__declspec(dllexport) __cdecl void lua_rawseti() { }
__declspec(dllexport) __cdecl void lua_remove() { }
__declspec(dllexport) __cdecl void lua_replace() { }
__declspec(dllexport) __cdecl void lua_resume() { }
__declspec(dllexport) __cdecl void lua_setallocf() { }
__declspec(dllexport) __cdecl void lua_setfenv() { }
__declspec(dllexport) __cdecl void lua_setfield() { }
__declspec(dllexport) __cdecl void lua_sethook() { }
__declspec(dllexport) __cdecl void lua_setlevel() { }
__declspec(dllexport) __cdecl void lua_setlocal() { }
__declspec(dllexport) __cdecl void lua_setmetatable() { }
__declspec(dllexport) __cdecl void lua_settable() { }
__declspec(dllexport) __cdecl void lua_settop() { }
__declspec(dllexport) __cdecl void lua_setupvalue() { }
__declspec(dllexport) __cdecl void lua_status() { }
__declspec(dllexport) __cdecl void lua_toboolean() { }
__declspec(dllexport) __cdecl void lua_tocfunction() { }
__declspec(dllexport) __cdecl void lua_tointeger() { }
__declspec(dllexport) __cdecl void lua_tolstring() { }
__declspec(dllexport) __cdecl void lua_tonumber() { }
__declspec(dllexport) __cdecl void lua_topointer() { }
__declspec(dllexport) __cdecl void lua_tothread() { }
__declspec(dllexport) __cdecl void lua_touserdata() { }
__declspec(dllexport) __cdecl void lua_type() { }
__declspec(dllexport) __cdecl void lua_typename() { }
__declspec(dllexport) __cdecl void lua_xmove() { }
__declspec(dllexport) __cdecl void lua_yield() { }
__declspec(dllexport) __cdecl void luaopen_base() { }
__declspec(dllexport) __cdecl void luaopen_debug() { }
__declspec(dllexport) __cdecl void luaopen_io() { }
__declspec(dllexport) __cdecl void luaopen_math() { }
__declspec(dllexport) __cdecl void luaopen_os() { }
__declspec(dllexport) __cdecl void luaopen_package() { }
__declspec(dllexport) __cdecl void luaopen_string() { }
__declspec(dllexport) __cdecl void luaopen_table() { }
